// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'F:/Project/项目/api/api-frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'F:/Project/项目/api/api-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { SmileOutlined, CrownOutlined };
